version: '3'
services:
  strapi:
    container_name: strapi
    build:
      context: .
      dockerfile: ./docker/${NODE_ENV}/Dockerfile
      args:
        NODE_ENV: development
    image: strapi:dev
    restart: unless-stopped
    env_file: .env.development
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: development
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/app/package.json
      - ./yarn.lock:/opt/app/yarn.lock
      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - '1337:1337'
    networks:
      - strapi_internal
    depends_on:
      - postgres

  postgres:
    image: postgres:12.0-alpine
    container_name: postgres
    platform: linux/amd64
    restart: unless-stopped
    env_file: .env.development
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - strapi-data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
    networks:
      - strapi_internal

volumes:
  strapi-data:

networks:
  strapi_internal:
    name: strapi_internal
    driver: bridge
